<?php

if (!defined("_VALID_PHP")) {die();}

return [
	// common

	'az' => 'Азербайджанский',
	'en' => 'Английский',
	'ru' => 'Русский',

	'access' => 'Доступ',
	'access_granted' => 'Разрешён',
	'access_prohibited' => 'Блокирован',
	'add' => 'Добавить',
	'alert' => 'Внимание!',
	'alert_success' => 'Прекрасно!',
	'alert_warning' => 'Внимание!',
	'alert_info' => 'Хозяйке на заметку!',
	'alert_danger' => 'Тысяча чертей!',
	'apply' => 'Применить',
	'author' => 'Автор',
	'back' => 'Назад',
	'cancel' => 'Отменить',
	'common_data' => 'Общая инф-я',
	'content' => 'Контент',
	'controls' => 'Управление',
	'del_suc' => 'Успешно удалено',
	'del_err' => 'Ошибка удаления',
	'delete' => 'Удалить',
	'delete_confirmation' => 'Вы уверены что хотите удалить эту запись?',
	'delete_confirmation_user' => 'Вы уверены что хотите удалить этого пользователя?',
	'edit' => 'Редактировать',
	'editor' => 'Редактор',
	'filter' => 'Фильтр',
	'filter_all' => 'Все',
	'filter_popup_title' => 'Дополнительные параметры',
	'filter_no_matter' => 'Не важно',
	'get_err' => 'Неверные параметры скрипта',
	'greetings' => 'Здравствуйте, ',
	'greetings_content' => 'Добро пожаловать в PROFIT CMS.<br /><br />Выберите раздел.',
    'helloAdmin' => 'Здравствуйте',
	'image' => 'Изображение',
	'insert_err' => 'Не удалось добавить данные',
	'insert_suc' => 'Успешно добавлено',
	'logout' => 'Выход',
	'lookAtSite' => 'На сайт',
	'main_page' => 'Главная',
	'more_info' => 'Подробнее',
	'no_data_found' => 'Данных не найдено',
	'pg' => 'постраничный вывод',
	'pg_all' => 'показать все',
	'pg_2end' => 'в конец',
	'pg_2start' => 'в начало',
	'pg_next' => 'следующая',
	'pg_prev' => 'предыдущая',
	'publish' => 'Опубликовать',
	'publish_lang' => 'опубликовать на этом языке',
	'publish_off' => 'Не опубликовано',
	'publish_on' => 'Опубликовано',
	'reset' => 'Отменить изменения',
	'resourses' => 'Ресурсы',
	'save' => 'Сохранить',
	'search' => 'Поиск',
	'search_query' => 'введите поисковой запрос',
	'show_site' => 'Показать сайт',
	'status' => 'Статус',
	'toggle_navigation' => 'Скрыть/показать меню',
	'update_err' => 'Не удалось сохранить изменения',
	'update_no_data_affected' => 'Изменений не было',
	'update_suc' => 'Данные успешно изменены',
	'view' => 'Просмотр',

	// Password Generator

	'password_generator' => 'Генератор пароля',
	'password_generator_approve' => 'Я скопировал пароль в безопасное место.',
	'password_generator_btn_cancel' => 'Отмена',
	'password_generator_btn_regenerate' => 'Сгенерировать ещё раз',
	'password_generator_btn_use' => 'Использовать этот',

	// javascript

	'js_alert' => 'Уведомление',
	'js_confirmation' => 'Подтвердите свое действие',
	'js_close' => 'Закрыть',
	'js_ok' => 'OK',
	'js_cancel' => 'Отмена',
	'js_confirm' => 'Подтвердить',

	// File Upload

	'upl_invalid_image_extension_err' => 'Разрешена загрузка файлов только с расширениями *.jpg, *.png',
	'upl_ini_size_err' => 'Общий объем данных превысил ограничение на сервере',
	'upl_form_size_err' => 'Превышен допустимый размер файла',
	'upl_partial_err' => 'Загрузка была прервана, повторите попытку',
	'upl_no_file_err' => 'Файл не выбран',
	'upl_no_tmp_dir_err' => 'Файл не удалось загрузить из-за ошибки на сервере',
	'upl_can_write_err' => 'Файл не удалось загрузить из-за ошибки на сервере',
	'upl_extension_err' => 'Файл не удалось загрузить из-за ошибки на сервере',
	'browse_placeholder' => 'Файл не выбран',
	'browse_button_text' => 'Обзор',

	// Notification E-mails & messages

	'password_recovery_subj' => 'Восстановление пароля',
	'password_recovery_msg' => '<h1>Здравствуйте {username}</h1><p>Для того чтобы сменить пароль перейдите по ссылке <a href="{recovery_link}">{recovery_link}</a></p>',

	// CMS - Log in

	'login_title' => 'Вход в админ-панель',
	'login_form_tip' => 'Вход в админ-панель',
	'login_email_placeholder' => 'Почта',
	'login_password_placeholder' => 'Пароль',
	'login_password_recovery' => 'Восстановить пароль',
	'login_remember_me' => 'Запомнить меня',
	'login_sign_in' => 'Войти',
	'login_social_facebook' => 'Войти с помощью Facebook',
	'login_social_googleplus' => 'Войти с помощью Google+',
	'login_err' => 'Неверный логин или пароль',
	'login_err_blocked' => 'Этот аккаунт заблокирован',
	'login_social_err' => 'Для этого пользователя ({usermail}, {username}) не зарегистрирован аккаунт',
	'login_suc' => 'Добро пожаловать',

	// CMS - Password recovery

	'password_recovery_title' => 'Восстановление доступа',
	'password_recovery_email_placeholder' => 'Почта',
	'password_recovery_form_tip' => 'Пожалуйста, введите свой электронный адрес. На него будет отправлена ссылка на страницу сброса пароля.',
	'password_recovery_login' => 'Или попробуйте войти под другим логином',
	'password_recovery_err_email_invalid' => 'Введите валидный адрес почтового ящика',
	'password_recovery_err_email_cannot_send' => 'Не получилось отправить письмо',
	'password_recovery_err_user_not_found' => 'Такой пользователь не зарегистирован',
	'password_recovery_suc_email_sended' => 'Письмо было успешно отправлено на ваш адрес {email}. Проверьте папки Входящие и Спам.',

	// CMS - Password change

	'password_change_title' => 'Смена пароля',
	'password_change_placeholder' => 'Введите новый пароль',
	'password_change_err_account_hash_expired' => 'Вы воспользовались устаревшей ссылкой',
	'password_change_suc' => 'Пароль успешно сохранен',

	// CMS - Action approve (screenlock)

	'password_approve_title' => 'Проверка безопасности',
	'password_approve_placeholder' => 'Пароль',
	'password_approve_descr' => 'Вы собираетесь совершить небезопасное действие. Чтобы продолжить введите свой пароль.',

	// 403

	'403_title' => '403',
	'403_headline' => 'Доступ запрещен',
	'403_descr' => 'Вам не предоставлен доступ к запрашиваемой странице. Обратитесь к администратору или <a href="?controller=base&amp;action=sign_out">смените пользователя</a>.',

	// 404

	'404_title' => '404',
	'404_headline' => 'Ой! Страница не найдена.',
	'404_descr' => 'Мы не смогли найти ту страницу которая вам нужна :( <!-- Meanwhile, you may <a href="{dashboard_link}">return to dashboard</a> or try using the search form. -->',

	// CMS menu blocks and items

	'menu_title' => 'Меню',
	'menu_block_dashboard' => 'Консоль',
	'menu_item_statistics_dashboard' => 'Обзор',
	'menu_block_site_users' => 'Модерация',
	'menu_item_site_users_list' => 'Пользователи',
	'menu_item_site_users_view_info' => 'Личные данные пользователя',
	'menu_item_comments_list' => 'Комментарии',
	'menu_item_comments_edit' => 'Модерировать комментарий',
	'menu_block_cms_users' => 'Администраторы',
	'menu_item_cms_users_list' => 'Пользователи',
	'menu_item_cms_users_add' => 'Добавить пользователя',
	'menu_item_cms_users_edit' => 'Редактировать пользователя',
	'menu_block_content' => 'Контент',
	'menu_block_nav' => 'Навигация',
	'menu_item_articles_list' => 'Публикации',
	'menu_item_articles_add' => 'Добавление публикации',
	'menu_item_articles_edit' => 'Редактировать публикацию',
	'menu_item_gallery_list' => 'Альбомы',
	'menu_item_gallery_add' => 'Добавить альбом',
	'menu_item_gallery_edit' => 'Редактировать альбом',
	'menu_item_gallery_photos' => 'Изображения',
	'menu_item_gallery_add_photo' => 'Добавить изображения в альбом',
	'menu_item_gallery_edit_photo' => 'Редактировать изображение',
	'menu_item_complaints' => 'Обратная связь',
	'menu_item_edit_admin_user_cats' => 'Разделы в ведении пользователя',
	'menu_item_edit_admin_user_privilegies' => 'Привилегии пользователя',
	'menu_block_settings' => 'Настройки сайта',
	'menu_item_site_languages' => 'Языковые версии',
	'menu_item_edit_lang' => 'Редактировать переводы в языковом файле',

	// Dashboard

	'dashboard_latest_members' => 'Последние зарегистрировавшиеся',
	'dashboard_new_members' => '{n} новы{ru:u1} пользовател{ru:u2}',
	'dashboard_view_all_users' => 'Посмотреть всех пользователей',
	'dashboard_articles_posted' => 'публикаци{ru:u1} занесен{ru:u2}',
	'dashboard_cms_users_count' => 'пользовател{ru:u1} CMS',

	// CMS users

	'add_cms_user' => 'Добавить пользователя',
	'cms_user_empty_login_err' => 'Логин не указан',
	'cms_user_edit_login_invalid_err' => 'Логин имеет неверный формат',
	'cms_user_duplicate_login_err' => 'Такой логин уже зарегистрирован',
	'cms_user_lang' => 'Язык интерфейса',
	'cms_user_lang_placeholder' => 'Выберите язык',
	'cms_user_lang_err' => 'Введённый вами язык отсутствует в системе',
	'cms_user_login' => 'Логин (адрес электронной почты)',
	'cms_user_name' => 'Имя',
	'cms_user_name_err' => 'Имя пользователя введено неверно или содержит запрещённые символы',
	'cms_user_new_pwd' => 'Новый пароль. Чтобы не вносить изменения оставьте поле пустым.',
	'cms_user_not_found' => 'Пользователь не найден',
	'cms_user_avatar' => 'Аватар',
	'cms_user_pwd' => 'Пароль',
	'cms_user_pwd_generate' => 'Сгенерировать',
	'cms_user_pwd_approve' => 'В целях безопасности, введите свой собственный пароль',
	'cms_user_pwd_approve_err' => 'Неверно указан пароль. Осталось %d попыток.',
	'cms_user_pwd_approve_self' => 'Старый пароль',
	'cms_user_pwd_repeat' => 'Подтвердите пароль',
	'cms_user_pwd_err' => 'Введенный вами пароль неверной длины либо имеет в составе запрещённые символы. Пароль может состоять из 6-64 цифр, букв и знаков препинания.',
	'cms_user_pwd_not_equal_err' => 'Пароли не совпадают',
	'cms_user_reg_date' => 'Дата регистрации',
	'cms_user_role' => 'Роль',
	'cms_users_role_admin' => 'Администратор',
	'cms_users_role_editor' => 'Редактор',
	'cms_user_role_placeholder' => 'Выберите роль',
	'cms_user_role_err' => 'Роль введена неверно',
	'cms_user_edit_err_not_found' => 'Пользователь не найден',
	'cms_user_edit_approvable_data_lost_err' => 'Упс, кажется данные потерялись :(',
	'cms_user_is_online' => 'Онлайн',
	'cms_users_list' => 'Список пользователей',
	'cms_users_list_details' => 'Найден{ru:u1} {count} пользовател{ru:u2}',
	'cms_users_search' => 'Поиск пользователей',
	//'cms_users_top_menu_item' => 'Администрация',
	'edit_cms_user' => 'Редактировать пользователя',
	'edit_cms_user_self' => 'Мой профиль',
	'cms_users_menu_section_allow' => 'Разрешить добавление и редактирование контента в этом разделе',

	// Photo Gallery

	'gallery' => 'Галерея',
	'gallery_list_details' => '{count} галере{ru:u1} найден{ru:u2}',
	'gallery_album_add' => 'Добавить альбом',
	'gallery_album_add_datetime' => 'Дата добавления',
	'gallery_album_edit' => 'Редактировать альбом',
	'gallery_album_name' => 'Название альбома',
	'gallery_albums_list' => 'Список альбомов',
	'gallery_name_empty' => 'Название альбома не может быть пустым',
	'gallery_not_found_err' => 'Галерея не найдена',
	'gallery_photo' => 'Картинка',
	'gallery_photo_add' => 'ещё одну',
	'gallery_photo_add_quantity_err' => 'Нельзя загружать более 20-и картинок',
	'gallery_photo_edit' => 'Редактировать картинку',
	'gallery_photo_name' => 'Название картинки',
	'gallery_photo_subtext' => 'Подпись к картинке',
	'gallery_photos_add' => 'Добавить картинки',
	'gallery_photos_list' => 'Список картинок',
	'gallery_photos_list_details' => '{count} изображени{ru:u1} найден{ru:u2}',
	'gallery_photos_num' => 'Кол-во картинок',
	'gallery_edit_err_name_empty' => 'Название альбома не может быть пустым',

	// languages - SITE languages

	'site_lang_code' => 'ISO 639-1',
	'site_lang_name' => 'Самоназвание языка',
	'site_lang_published' => 'Опубликован',
	'site_lang_add_popup_title' => 'Добавить на сайт новую языковую версию',
	'site_lang_add_popup_descr' => 'После добавления новой языковой версии вы сможете перевести фразы и оповещения сайта. <strong>Не публикуйте</strong> языковую версию пока не убедитесь что все фразы и хотя бы основные пункты меню переведены. Также необходимо учесть что при переходе на языковую версию статьи для которой нет перевода будет показана 404 ошибка.',
	'site_lang_add_err_invalid_code' => 'ISO 639-1 код введен неверно',
	'site_lang_add_err_duplicate_code' => 'Введенный код ISO 639-1 уже зарегистрирован',
	'site_lang_add_err_invalid_name' => 'Введите самоназвание языка',
	'site_lang_tr_key' => 'Ключ',
	'site_lang_tr_value' => 'Перевод',
	'site_lang_tr_value_not_translated' => 'Не переведено',

	// Content - Articles

	'article_category' => 'Категория',
	'article_category_none' => 'Без категории',
	'article_sef' => 'ЧПУ / SEF (человеко-понятный URL)',
	'article_sef_descr' => 'Рекомендуется вводить перевод заголовка статьи на английский язык.<br />Текст будет преобразован к формату, пригодному для URL автоматически.',
	'article_source' => 'Оригинал публикации',
	'article_source_url' => 'Ссылка',
	'article_source_name' => 'Название ресурса',
	'article_image_descr' => 'Разрешена загрузка файлов {types} типов.',
	'article_image_original_view' => 'Оригинал',
	'article_image_original_size' => 'Размер оригинала',
	'article_image_original_upload_datetime' => 'Загружено на сервер',
	'article_image_thumbnail_size' => 'Размер эскиза',
	'articles_list_details' => 'Найден{ru:u1} {count} публикаци{ru:u2}',
	'article_publish_datetime' => 'Дата и время когда статья будет опубликована',
	'article_publish_date_placeholder' => 'Дата',
	'article_publish_hour_placeholder' => 'Часы',
	'article_publish_minutes_placeholder' => 'Минуты',
	'article_gallery' => 'Галерея',
	'article_author' => 'Создатель',
	'article_title' => 'Заголовок',
	'article_keywords' => 'Ключевые слова',
	'article_short' => 'Короткий текст',
	'article_full' => 'Текст',
	'article_show_on_main_page' => 'Отображать на главной странице',
	'article_show_on_main_page_filter' => 'Показываемые на главной',
	'article_show_off_main_page_filter' => 'Не показываемые на главной',
	'article_is_highlighted' => 'Избранное',
	'article_is_highlighted_filter' => 'Избранные',
	'article_add_err_title_empty' => 'Заголовок не должен быть пустым',
	'article_add_err_full_empty' => 'Текст публикации не должен быть пустым',
	'article_add_err_publish_date_invalid' => 'Дата публикации введена неверно',
	'article_add_err_publish_hour_invalid' => 'Час времени публикации указан неверно',
	'article_add_err_publish_minutes_invalid' => 'Минуты времени публикации указаны неверно',
	'article_add_err_gallery_not_exists' => 'Галерея не найдена',
	'article_add_err_source_url_invalid' => 'URL оригинала введен не верно',
	'article_edit_err_not_found' => 'Публикация не найдена',
	'article_edit_err_sef_empty' => 'ЧПУ публикации не может быть пустым',
	'articles_assignment' => 'Доп. привязка',

	// Navigation

	'nav_menu' => 'Меню',
	'nav_menu_structure' => 'Структура меню',
	'nav_menu_add_item' => 'Добавить вложенный элемент',
	'nav_menu_del_item' => 'Удалить выбранный элемент',
	'nav_menu_edit_item' => 'Просмотр / Редактирование элемента',
	'nav_menu_item_name' => 'Название',
	'nav_menu_item_type' => 'Тип',
	'nav_menu_item_type_article' => 'Публикация',
	'nav_menu_item_type_category' => 'Категория',
	'nav_menu_item_type_spec' => 'Спецстраница',
	'nav_menu_item_type_url' => 'Ссылка',
	'nav_menu_item_sef' => 'ЧПУ (должен быть уникальным)',
	'nav_menu_item_ref_article' => 'Выберите публикацию (автозаполнение с 2-ух символов)',
	'nav_menu_item_url' => 'URL',
	'nav_menu_item_url_descr' => 'Если элемент используется только для создания подменю и не имеет собственной страницы, оставьте символ &laquo;#&raquo;.<br />
	Если URL является локальным для этого сайта, адрес должен начинаться с &laquo;/&raquo;.<br />
	Все остальные адреса будут трактоваться как глобальные и останутся без изменений.<br />
	Также допустимо использование вайлдкарда {lang} для динамического указания в адресе языковой версии.',
	'nav_menu_item_position' => 'Позиция',
	'nav_menu_item_is_section' => 'Раздел (категория или спецстраница, содержащая контент и имеющая возможность назначения редактору для заполнения)',
	'nav_menu_add_item_err_type_invalid' => 'Тип указан неверно',
	'nav_menu_add_item_err_sef_invalid' => 'ЧПУ указан неверно',
	'nav_menu_add_item_err_sef_exists' => 'Указанный ЧПУ уже использован',
	'nav_menu_add_item_err_article_id_empty' => 'Не выбрана публикация',
	'nav_menu_add_item_err_article_id_not_exists' => 'Указанной публикации не существует',
	'nav_menu_add_item_err_article_id_item_exists' => 'Указанная публикация уже была использована в меню',
	'nav_menu_add_item_err_name_empty' => 'Введите название',
	'nav_menu_add_item_err_position_empty' => 'Ни одной позиции не выбрано',
	'nav_menu_edit_item_err_not_found' => 'Элемент не найден',
	'nav_menu_level_up' => 'Вверх',

	// Moderation - Site users

	'site_users_list_details' => 'Найден{ru:u1} {count} пользовател{ru:u2}',
	'site_users_has_registered' => 'пользовател{ru:u1} зарегистрировал{ru:u2}',
	'site_user_profile_info' => 'Профиль',
	'site_user_email' => 'E-mail',
	'site_user_name' => 'Имя, фамилия',
	'site_user_reg_date' => 'Дата регистрации',
	'site_user_reg_date_since' => 'с',
	'site_user_reg_date_till' => 'по',
	'site_users_provider' => 'Провайдер',
	'site_users_provider_none' => 'Самостоятельный пользователь',
	'site_user_nickname' => 'Ник',
	'site_user_birth_date' => 'Дата рождения',
	'site_user_gender' => 'Пол',
	'site_user_gender_male' => 'Мужской',
	'site_user_gender_female' => 'Женский',
	'site_user_registration_datetime' => 'Дата регистрации',
	'site_user_last_login_datetime' => 'Дата последнего входа',
	'site_user_comments_count' => 'Оставлено комментариев',

	// Moderation - Comments

	'comments_list_details' => 'Найден{ru:u1} {count} комментари{ru:u2}',
	'comments_are_left' => 'комментари{ru:u1} оставлен{ru:u2}',
	'comments_user' => 'Пользователь',
	'comments_preambula' => 'Текст',
	'comment_text' => 'Текст',
	'comments_posted_datetime' => 'Дата',
	'comments_posted_datetime_since' => 'с',
	'comments_posted_datetime_till' => 'по',
	'comments_is_published' => 'Опубликован',
	'comments_is_inspected' => 'Просмотрен',
	'comment_inspected' => 'Просмотрен',
	'comment_not_inspected' => 'Не просмотрен',
	'comments_moderate' => 'Модерация',
	'comments_moderate_allow' => 'Допустить',
	'comments_moderate_deny' => 'Запретить',

	// Moderation - Feedback

	'complaints_chat_list' => 'Переписки',
	'complaints_username' => 'Имя пользователя',
	'complaints_last_msg_date' => 'Дата последнего сообщения',
	'complaints_last_msg_short' => 'Выдержка из последнего сообщения',
    'complaints_answeredness' => 'Отвеченность',
    'complaints_answeredness_all' => 'Все',
    'complaints_answeredness_not' => 'Не отвеченные',
    'complaints_answeredness_yep' => 'Отвеченные',
	'complaints_answer_notification_sms' => 'Ваше обращение было рассмотрено',
	'complaints_answer_notification_subj' => 'Ваше обращение было рассмотрено',
	'complaints_answer_notification_email' => '<h1 style="font-size: medium; font-family: serif; font-weight: normal;">Уважаемый {username},</h1><p style="font-size: medium; font-family: serif; font-weight: normal;">Ваше обращение было рассмотрено:</p><blockquote> {answer} </blockquote><p style="font-size: medium; font-family: serif; font-weight: normal;">Текст обращения:</p><blockquote> {complaint} </blockquote>',
    'complaints_message_err' => 'Введите текст',
    'complaints_file_err' => 'Неверный формат файла',
	'complaints_chat_with' => 'Переписка с пользователем {username}',
	'complaints_answered' => 'Обращение успешно отвечено',
	'complaints_give_answer' => 'Ответить',

];

?>